# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift 6

on:   
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build Swift
    strategy:
      matrix:
        swift: ["5.9", "5.10", "6.0"]

    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Swift
      run: |
        curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash -s -- --disable-confirmation
        swiftly install ${{ matrix.swift }}
        swiftly use ${{ matrix.swift }}

    - name: Get Swift version
      run: swift --version

    - name: Run tests
      run: |
        swift build --build-tests
        swift test